name: Bug Report
description: Report a bug or incorrect behavior in TornAPIWrapper
labels: bug
body:
  - type: markdown
    attributes:
      description: >
        Thank you for reporting a bug!<br>
        Please make sure this is an issue with TornAPIWrapper itself and not the external API.

  - type: input
    attributes:
      label: Summary
      description: Briefly describe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the issue
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Code Example
      description: A short snippet that reproduces the issue
      render: python

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened (include full traceback if applicable)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version Info
      description: Paste the full output of `python -m TornAPIWrapper -v`
      render: shell
      placeholder: |
        - Python v...
        - TornAPIWrapper v...
        - requests v...
        - system info: ...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version of TornAPIWrapper
          required: true
        - label: I have removed any sensitive information (API keys, tokens, etc.)
          required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Anything else that might help